import { mkdtemp, readFile, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
	deriveDevProfile,
	expandPlaceholders,
	parseProfileDocument,
	renderClientEnv,
	renderServerEnv,
	writeManagedEnvFiles,
} from "./devProfile";

const localProfile = {
	kind: "local" as const,
	wranglerEnv: "local" as const,
	browserOrigin: "http://localhost:5173",
	apiOrigin: "http://127.0.0.1:8787",
};

describe("dev profile BDD", () => {
	it("derives one browser origin for Vite, CORS, and Auth redirects", () => {
		const profile = deriveDevProfile(localProfile, {
			apiUrl: "http://127.0.0.1:54321",
			publishableKey: "local-publishable",
			databaseUrl: "postgresql://postgres:postgres@127.0.0.1:54322/postgres",
			mailpitUrl: "http://127.0.0.1:54324",
			serviceRoleKey: "local-service-role",
		});

		expect(profile.vite).toEqual({ host: "localhost", port: 5173 });
		expect(profile.serverEnv.CORS_ORIGIN).toBe(localProfile.browserOrigin);
		expect(profile.serverEnv.SUPABASE_AUTH_REDIRECT_URL).toBe(
			`${localProfile.browserOrigin}/login`,
		);
		expect(profile.clientEnv.VITE_API_BASE_URL).toBe(
			"http://127.0.0.1:8787/api/v1",
		);
	});

	it("expands only exact shell placeholders and rejects unresolved interpolation", () => {
		expect(
			expandPlaceholders(
				{ value: `\${REMOTE_KEY}` },
				{ REMOTE_KEY: "resolved" },
			),
		).toEqual({ value: "resolved" });
		expect(() =>
			expandPlaceholders({ value: `prefix-\${REMOTE_KEY}` }, {}),
		).toThrow(/exact placeholder/i);
		expect(() => expandPlaceholders({ value: `\${REMOTE_KEY}` }, {})).toThrow(
			/REMOTE_KEY/,
		);
	});

	it("rejects mismatched discriminators and unsafe remote pooler ports", () => {
		expect(() =>
			parseProfileDocument({
				version: 1,
				profiles: { local: { ...localProfile, wranglerEnv: "remote" } },
			}),
		).toThrow();

		expect(() =>
			deriveDevProfile({
				kind: "remote",
				wranglerEnv: "remote",
				browserOrigin: "http://localhost:5173",
				apiOrigin: "http://127.0.0.1:8787",
				supabaseUrl: "https://example.supabase.co",
				supabasePublishableKey: "publishable",
				databaseConnectionString:
					"postgresql://postgres:password@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres",
			}),
		).toThrow(/5432/);
	});

	it("renders deterministic managed files without frontend secrets", () => {
		const resolved = deriveDevProfile(localProfile, {
			apiUrl: "http://127.0.0.1:54321",
			publishableKey: "local-publishable",
			databaseUrl: "postgresql://postgres:postgres@127.0.0.1:54322/postgres",
			mailpitUrl: "http://127.0.0.1:54324",
			serviceRoleKey: "local-service-role",
		});

		expect(renderServerEnv(resolved)).toMatchInlineSnapshot(`
      "# golden-years-dev-profile:v1
      # Generated by pnpm dev:profile:sync. Do not edit.
      CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE=postgresql://postgres:postgres@127.0.0.1:54322/postgres
      CORS_ORIGIN=http://localhost:5173
      SUPABASE_AUTH_REDIRECT_URL=http://localhost:5173/login
      SUPABASE_PUBLISHABLE_KEY=local-publishable
      SUPABASE_URL=http://127.0.0.1:54321
      "
    `);
		expect(renderClientEnv(resolved)).not.toMatch(
			/SUPABASE|DATABASE|postgres/i,
		);
	});

	it("refuses symlinks and backs up unmanaged files only with force", async () => {
		const directory = await mkdtemp(path.join(tmpdir(), "gy-dev-profile-"));
		const serverPath = path.join(directory, "server.env");
		const clientPath = path.join(directory, "client.env");
		const target = path.join(directory, "target.env");
		await writeFile(target, "target", "utf8");
		await symlink(target, serverPath);

		await expect(
			writeManagedEnvFiles({
				serverPath,
				clientPath,
				serverContent: "server",
				clientContent: "client",
			}),
		).rejects.toThrow(/symlink/i);

		await writeFile(`${serverPath}.plain`, "operator-owned", "utf8");
		const result = await writeManagedEnvFiles({
			serverPath: `${serverPath}.plain`,
			clientPath,
			serverContent: "server",
			clientContent: "client",
			force: true,
			backupTimestamp: "20260705T000000Z",
		});

		expect(result.backups).toHaveLength(1);
		expect(await readFile(result.backups[0], "utf8")).toBe("operator-owned");
	});
});
