import type { ArticleRow, FacilityRow, ReferenceItemRow, ReviewRow, UserRow } from "@/db/schema/types";

const now = new Date("2026-05-18T00:00:00.000Z");

export const seedUsers: UserRow[] = [
  {
    id: "usr_family_demo",
    email: "family@example.com",
    display_name: "Family Demo",
    password_hash: "sha256:5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
    status: "active",
    created_at: now,
    updated_at: now,
  },
];

export const seedReferenceItems: ReferenceItemRow[] = [
  {
    id: "independent",
    kind: "care_type",
    name: "Independent Living",
    metadata: { short: "For active seniors who want community, hospitality and security." },
    sort_order: 10,
    created_at: now,
    updated_at: now,
  },
  {
    id: "assisted",
    kind: "care_type",
    name: "Assisted Living",
    metadata: { short: "Support with activities of daily living." },
    sort_order: 20,
    created_at: now,
    updated_at: now,
  },
  {
    id: "central",
    kind: "region",
    name: "Central",
    metadata: { districts: ["Bukit Timah", "Toa Payoh"] },
    sort_order: 10,
    created_at: now,
    updated_at: now,
  },
  {
    id: "med247",
    kind: "feature",
    name: "24/7 medical staff",
    metadata: { category: "Medical" },
    sort_order: 10,
    created_at: now,
    updated_at: now,
  },
  {
    id: "english",
    kind: "language",
    name: "English",
    metadata: { official: true },
    sort_order: 10,
    created_at: now,
    updated_at: now,
  },
];

export const seedFacilities: FacilityRow[] = [
  {
    id: "fac_orchid_gardens",
    slug: "orchid-gardens",
    name: "Orchid Gardens Retirement Living",
    tagline: "Resort-style independent living in the heart of Bukit Timah.",
    status: "approved",
    is_enabled: true,
    care_types: ["independent", "assisted"],
    region_id: "central",
    district: "Bukit Timah",
    address: "12 Orchid Drive, Singapore 269710",
    postal_code: "269710",
    price_from: 6800,
    price_unit: "month",
    rating: 4.8,
    review_count: 42,
    image_url: "https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=900",
    gallery_urls: [
      "https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=1200",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200",
    ],
    features: ["med247", "physio", "private_room", "garden", "ensuite", "activities"],
    languages: ["English", "Mandarin", "Hokkien"],
    capacity: 120,
    year_opened: 2018,
    licence: "MOH-RH-2018-014",
    about:
      "Set in five acres of landscaped gardens minutes from Botanic Gardens, Orchid Gardens combines resort-style hospitality with quietly attentive care.",
    highlights: ["Private apartments", "Concierge and dining", "Care plans that scale"],
    right_for_you_if: ["You want a residence that scales without moving rooms."],
    latitude: 1.3503,
    longitude: 103.7755,
    availability_status: "available",
    beds_available: 3,
    availability_note: "Suite and one-bedroom apartments open.",
    availability_updated_at: new Date("2026-05-09T07:30:00.000Z"),
    provider_contact_email: "provider-private@example.com",
    admin_notes: "Private admin note",
    moderation_state: "approved",
    version: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "fac_serene_heights",
    slug: "serene-heights",
    name: "Serene Heights Assisted Care",
    tagline: "Warm, family-style assisted living in Toa Payoh.",
    status: "approved",
    is_enabled: true,
    care_types: ["assisted", "respite"],
    region_id: "central",
    district: "Toa Payoh",
    address: "88 Lorong 6 Toa Payoh, Singapore 319395",
    postal_code: "319395",
    price_from: 3200,
    price_unit: "month",
    rating: 4.6,
    review_count: 67,
    image_url: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=900",
    gallery_urls: ["https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=1200"],
    features: ["med247", "physio", "halal", "vegetarian", "wheelchair", "subsidy"],
    languages: ["English", "Mandarin", "Malay"],
    capacity: 80,
    year_opened: 2015,
    licence: "MOH-RH-2015-082",
    about: "Serene Heights is a mid-sized home that prides itself on a family atmosphere.",
    highlights: ["Subsidy eligible", "Halal and vegetarian kitchens"],
    right_for_you_if: ["You want a homely, mid-sized place."],
    latitude: 1.3355,
    longitude: 103.8505,
    availability_status: "limited",
    beds_available: 1,
    availability_note: "Single private room on level 3.",
    availability_updated_at: new Date("2026-05-11T07:30:00.000Z"),
    provider_contact_email: "private-serene@example.com",
    admin_notes: "Do not expose",
    moderation_state: "approved",
    version: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "fac_bayshore_nursing",
    slug: "bayshore-nursing",
    name: "Bayshore Nursing Home",
    tagline: "Skilled nursing care with sea views in Pasir Ris.",
    status: "approved",
    is_enabled: true,
    care_types: ["nursing", "hospice"],
    region_id: "east",
    district: "Pasir Ris",
    address: "5 Pasir Ris Coast Road, Singapore 519536",
    postal_code: "519536",
    price_from: 3800,
    price_unit: "month",
    rating: 4.4,
    review_count: 51,
    image_url: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=900",
    gallery_urls: ["https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=1200"],
    features: ["med247", "physio", "tcm", "hospice"],
    languages: ["English", "Mandarin", "Malay", "Tamil"],
    capacity: 160,
    year_opened: 2012,
    licence: "MOH-NH-2012-031",
    about: "Bayshore Nursing Home provides skilled nursing care in Pasir Ris.",
    highlights: ["Sea views", "Skilled nursing team"],
    right_for_you_if: ["You need round-the-clock nursing care."],
    latitude: 1.3815,
    longitude: 103.9556,
    availability_status: "waitlist",
    beds_available: 0,
    availability_note: "Waitlist currently open.",
    availability_updated_at: new Date("2026-05-08T07:30:00.000Z"),
    provider_contact_email: "private-bay@example.com",
    admin_notes: "Internal note",
    moderation_state: "approved",
    version: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "fac_hidden_draft",
    slug: "hidden-draft",
    name: "Hidden Draft Home",
    tagline: "This record must not appear publicly.",
    status: "draft",
    is_enabled: true,
    care_types: ["assisted"],
    region_id: "west",
    district: "Jurong",
    address: "Private",
    postal_code: "000000",
    price_from: 1000,
    price_unit: "month",
    rating: 0,
    review_count: 0,
    image_url: "",
    gallery_urls: [],
    features: [],
    languages: ["English"],
    capacity: null,
    year_opened: null,
    licence: null,
    about: "",
    highlights: [],
    right_for_you_if: [],
    latitude: null,
    longitude: null,
    availability_status: "unavailable",
    beds_available: null,
    availability_note: null,
    availability_updated_at: null,
    provider_contact_email: "private-hidden@example.com",
    admin_notes: "Hidden from public",
    moderation_state: "draft",
    version: 1,
    created_at: now,
    updated_at: now,
  },
];

export const seedReviews: ReviewRow[] = [
  {
    id: "rev_1",
    facility_id: "fac_orchid_gardens",
    author_name: "Mei Lin T.",
    relationship: "Daughter of resident",
    rating: 5,
    review_date: "2026-03-12",
    title: "Mum is genuinely happy here",
    body: "The staff learned her routine quickly and the activities programme has given her a new circle of friends.",
    verified: true,
    status: "published",
    version: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "rev_2",
    facility_id: "fac_serene_heights",
    author_name: "Aisyah B.",
    relationship: "Daughter-in-law",
    rating: 5,
    review_date: "2026-04-02",
    title: "Halal kitchen made all the difference",
    body: "Staff speak Malay and the family lounge is genuinely comfortable for visits.",
    verified: true,
    status: "published",
    version: 1,
    created_at: now,
    updated_at: now,
  },
];

export const seedArticles: ArticleRow[] = [
  {
    id: "art_how_to_tour",
    slug: "how-to-tour-a-care-home",
    title: "How to tour a care home",
    excerpt: "Questions to ask and details to notice during a visit.",
    body: "Focus on care routines, staffing, meals, activities, safety, and how the home communicates with families.",
    category: "guides",
    status: "published",
    published_at: now,
  },
];
